import { WorkflowCategory, WorkflowPreset } from "./types";

export const workflowNodeWidth = 150;
export const workflowNodeBaseHeight = 92;
export const workflowEndpointStartY = 48;
export const workflowEndpointGap = 28;

export const workflowPresets: WorkflowPreset[] = [
    {
        category: "input",
        description: "Provides a numeric value",
        icon: "A",
        inputs: [],
        outputs: [{ label: "value", valueType: "number" }],
        title: "Number Input",
        type: "number-input",
    },
    {
        category: "input",
        description: "Provides a boolean value",
        icon: "B",
        inputs: [],
        outputs: [{ label: "value", valueType: "boolean" }],
        title: "Boolean Input",
        type: "boolean-input",
    },
    {
        category: "input",
        description: "Provides a text value",
        icon: "T",
        inputs: [],
        outputs: [{ label: "text", valueType: "text" }],
        title: "Text Input",
        type: "text-input",
    },
    {
        category: "input",
        description: "Outputs a constant value",
        icon: "C",
        inputs: [],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Constant",
        type: "constant-input",
    },
    {
        category: "input",
        description: "Reads a variable value",
        icon: "V",
        inputs: [],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Variable",
        type: "variable-input",
    },
    {
        category: "math",
        description: "Adds two numbers",
        icon: "+",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "sum", valueType: "number" }],
        title: "Add",
        type: "math-add",
    },
    {
        category: "math",
        description: "Subtracts two numbers",
        icon: "-",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "difference", valueType: "number" }],
        title: "Subtract",
        type: "math-subtract",
    },
    {
        category: "math",
        description: "Multiplies two numbers",
        icon: "x",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "product", valueType: "number" }],
        title: "Multiply",
        type: "math-multiply",
    },
    {
        category: "math",
        description: "Divides two numbers",
        icon: "/",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "quotient", valueType: "number" }],
        title: "Divide",
        type: "math-divide",
    },
    {
        category: "math",
        description: "Rounds a number",
        icon: "~",
        inputs: [{ label: "value", valueType: "number" }],
        outputs: [{ label: "rounded", valueType: "number" }],
        title: "Round",
        type: "math-round",
    },
    {
        category: "logic",
        description: "Checks if a > b",
        icon: ">",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Greater Than",
        type: "logic-greater-than",
    },
    {
        category: "logic",
        description: "Checks if a < b",
        icon: "<",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Less Than",
        type: "logic-less-than",
    },
    {
        category: "logic",
        description: "Checks if a == b",
        icon: "==",
        inputs: [
            { label: "a", valueType: "any" },
            { label: "b", valueType: "any" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Equal",
        type: "logic-equal",
    },
    {
        category: "logic",
        description: "Logical AND",
        icon: "&&",
        inputs: [
            { label: "left", valueType: "boolean" },
            { label: "right", valueType: "boolean" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "And",
        type: "logic-and",
    },
    {
        category: "logic",
        description: "Logical OR",
        icon: "||",
        inputs: [
            { label: "left", valueType: "boolean" },
            { label: "right", valueType: "boolean" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Or",
        type: "logic-or",
    },
    {
        category: "logic",
        description: "Logical NOT",
        icon: "!",
        inputs: [{ label: "value", valueType: "boolean" }],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Not",
        type: "logic-not",
    },
    {
        category: "logic",
        description: "Routes a value through multiple ordered cases",
        icon: "↬",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [
            { label: "case 1", valueType: "any" },
            { label: "case 2", valueType: "any" },
            { label: "default", valueType: "any" },
        ],
        styleVariant: "switch-case",
        title: "Switch Case",
        type: "logic-switch",
    },
    {
        category: "logic",
        description: "Runs one of two paths based on a condition",
        icon: "IF",
        inputs: [{ label: "condition", valueType: "boolean" }],
        outputs: [
            { label: "if", valueType: "any" },
            { label: "else", valueType: "any" },
        ],
        styleVariant: "if-else",
        title: "If / Else",
        type: "logic-if-else",
    },
    {
        category: "utility",
        description: "Formats any value",
        icon: "F",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [{ label: "text", valueType: "text" }],
        title: "Format",
        type: "utility-format",
    },
    {
        category: "utility",
        description: "Converts value type",
        icon: "C",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [{ label: "converted", valueType: "any" }],
        title: "Convert",
        type: "utility-convert",
    },
    {
        category: "utility",
        description: "Returns first non-null value",
        icon: "Co",
        inputs: [
            { label: "left", valueType: "any" },
            { label: "right", valueType: "any" },
        ],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Coalesce",
        type: "utility-coalesce",
    },
    {
        category: "utility",
        description: "Delays execution",
        icon: "D",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Delay",
        type: "utility-delay",
    },
    {
        category: "output",
        description: "Outputs a final result",
        icon: "R",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [],
        title: "Result",
        type: "result-output",
    },
    {
        category: "output",
        description: "Logs a message",
        icon: "L",
        inputs: [{ label: "message", valueType: "any" }],
        outputs: [],
        title: "Log",
        type: "log-output",
    },
    {
        category: "output",
        description: "Shows an alert",
        icon: "A",
        inputs: [{ label: "message", valueType: "any" }],
        outputs: [],
        title: "Alert",
        type: "alert-output",
    },
];

export const workflowCategoryLabels: Record<WorkflowCategory, string> = {
    input: "Input",
    math: "Math",
    logic: "Logic",
    utility: "Utility",
    output: "Output",
};

export const workflowPresetByType = new Map(workflowPresets.map((preset) => [preset.type, preset]));
