import { WorkflowCategory, WorkflowPreset, WorkflowThresholdBranch } from "./types";

export const workflowNodeWidth = 150;
export const workflowNodeBaseHeight = 92;
export const workflowEndpointStartY = 48;
export const workflowEndpointGap = 28;

export const defaultDecisionTableBranches = [
    { id: "normal", label: "normal", default: true },
    { id: "warning", label: "warning", comparator: ">=", threshold: "70" },
    { id: "critical", label: "critical", comparator: ">=", threshold: "90" },
] as const satisfies readonly WorkflowThresholdBranch[];

export const defaultThresholdPolicyBranches = defaultDecisionTableBranches;

export const workflowPresets: WorkflowPreset[] = [
    {
        category: "input",
        description: "Provides a numeric value",
        icon: "A",
        inputs: [],
        outputs: [{ label: "value", valueType: "number" }],
        title: "Number Input",
        type: "number-input",
    },
    {
        category: "input",
        description: "Provides a boolean value",
        icon: "B",
        inputs: [],
        outputs: [{ label: "value", valueType: "boolean" }],
        title: "Boolean Input",
        type: "boolean-input",
    },
    {
        category: "input",
        description: "Provides a text value",
        icon: "T",
        inputs: [],
        outputs: [{ label: "text", valueType: "text" }],
        title: "Text Input",
        type: "text-input",
    },
    {
        category: "input",
        description: "Outputs a constant value",
        icon: "C",
        inputs: [],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Constant",
        type: "constant-input",
    },
    {
        category: "input",
        description: "Reads a variable value",
        icon: "V",
        inputs: [],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Variable",
        type: "variable-input",
    },
    {
        category: "math",
        description: "Adds two numbers",
        icon: "+",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "sum", valueType: "number" }],
        title: "Add",
        type: "math-add",
    },
    {
        category: "math",
        description: "Subtracts two numbers",
        icon: "-",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "difference", valueType: "number" }],
        title: "Subtract",
        type: "math-subtract",
    },
    {
        category: "math",
        description: "Multiplies two numbers",
        icon: "x",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "product", valueType: "number" }],
        title: "Multiply",
        type: "math-multiply",
    },
    {
        category: "math",
        description: "Divides two numbers",
        icon: "/",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "quotient", valueType: "number" }],
        title: "Divide",
        type: "math-divide",
    },
    {
        category: "math",
        description: "Rounds a number",
        icon: "~",
        inputs: [{ label: "value", valueType: "number" }],
        outputs: [{ label: "rounded", valueType: "number" }],
        title: "Round",
        type: "math-round",
    },
    {
        category: "logic",
        description: "Checks if a > b",
        icon: ">",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Greater Than",
        type: "logic-greater-than",
    },
    {
        category: "logic",
        description: "Checks if a < b",
        icon: "<",
        inputs: [
            { label: "a", valueType: "number" },
            { label: "b", valueType: "number" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Less Than",
        type: "logic-less-than",
    },
    {
        category: "logic",
        description: "Checks if a == b",
        icon: "==",
        inputs: [
            { label: "a", valueType: "any" },
            { label: "b", valueType: "any" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Equal",
        type: "logic-equal",
    },
    {
        category: "logic",
        description: "Logical AND",
        icon: "&&",
        inputs: [
            { label: "left", valueType: "boolean" },
            { label: "right", valueType: "boolean" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "And",
        type: "logic-and",
    },
    {
        category: "logic",
        description: "Logical OR",
        icon: "||",
        inputs: [
            { label: "left", valueType: "boolean" },
            { label: "right", valueType: "boolean" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Or",
        type: "logic-or",
    },
    {
        category: "logic",
        description: "Logical NOT",
        icon: "!",
        inputs: [{ label: "value", valueType: "boolean" }],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Not",
        type: "logic-not",
    },
    {
        category: "logic",
        description: "Routes a value through multiple ordered cases",
        icon: "↬",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [
            { label: "case 1", valueType: "any" },
            { label: "case 2", valueType: "any" },
            { label: "default", valueType: "any" },
        ],
        styleVariant: "switch-case",
        title: "Switch Case",
        type: "logic-switch",
    },
    {
        category: "logic",
        description: "Runs one of two paths based on a condition",
        icon: "IF",
        inputs: [{ label: "condition", valueType: "boolean" }],
        outputs: [
            { label: "if", valueType: "any" },
            { label: "else", valueType: "any" },
        ],
        styleVariant: "if-else",
        title: "If / Else",
        type: "logic-if-else",
    },
    {
        category: "policy",
        description: "Routes a value through ordered decision branches",
        icon: "DT",
        inputs: [{ label: "value", valueType: "number" }],
        outputs: defaultDecisionTableBranches.map((branch) => ({ label: branch.label, valueType: "any" })),
        styleVariant: "threshold-policy",
        title: "Decision Table",
        type: "policy-decision-table",
    },
    {
        category: "utility",
        description: "Formats any value",
        icon: "F",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [{ label: "text", valueType: "text" }],
        title: "Format",
        type: "utility-format",
    },
    {
        category: "utility",
        description: "Converts value type",
        icon: "C",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [{ label: "converted", valueType: "any" }],
        title: "Convert",
        type: "utility-convert",
    },
    {
        category: "utility",
        description: "Returns first non-null value",
        icon: "Co",
        inputs: [
            { label: "left", valueType: "any" },
            { label: "right", valueType: "any" },
        ],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Coalesce",
        type: "utility-coalesce",
    },
    {
        category: "utility",
        description: "Delays execution",
        icon: "D",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Delay",
        type: "utility-delay",
    },
    {
        category: "output",
        description: "Outputs a final result",
        icon: "R",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [],
        title: "Result",
        type: "result-output",
    },
    {
        category: "output",
        description: "Logs a message",
        icon: "L",
        inputs: [{ label: "message", valueType: "any" }],
        outputs: [],
        title: "Log",
        type: "log-output",
    },
    {
        category: "output",
        description: "Shows an alert",
        icon: "A",
        inputs: [{ label: "message", valueType: "any" }],
        outputs: [],
        title: "Alert",
        type: "alert-output",
    },
    // Data / collection
    {
        category: "data",
        description: "Provides an array value",
        icon: "[]",
        inputs: [],
        outputs: [{ label: "array", valueType: "any" }],
        title: "Array Input",
        type: "array-input",
    },
    {
        category: "data",
        description: "Provides an object value",
        icon: "{}",
        inputs: [],
        outputs: [{ label: "object", valueType: "any" }],
        title: "Object Input",
        type: "object-input",
    },
    {
        category: "data",
        description: "Transforms each item in an array",
        icon: "↦",
        inputs: [{ label: "array", valueType: "any" }],
        outputs: [{ label: "result", valueType: "any" }],
        title: "Array Map",
        type: "array-map",
    },
    {
        category: "data",
        description: "Filters items in an array",
        icon: "⊇",
        inputs: [{ label: "array", valueType: "any" }],
        outputs: [{ label: "result", valueType: "any" }],
        title: "Array Filter",
        type: "array-filter",
    },
    {
        category: "data",
        description: "Reduces an array to a single value",
        icon: "∑",
        inputs: [
            { label: "array", valueType: "any" },
            { label: "initial", valueType: "any" },
        ],
        outputs: [{ label: "result", valueType: "any" }],
        title: "Array Reduce",
        type: "array-reduce",
    },
    {
        category: "data",
        description: "Reads a property from an object",
        icon: "→",
        inputs: [
            { label: "object", valueType: "any" },
            { label: "key", valueType: "text" },
        ],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Object Get",
        type: "object-get",
    },
    {
        category: "data",
        description: "Sets a property on an object",
        icon: "←",
        inputs: [
            { label: "object", valueType: "any" },
            { label: "key", valueType: "text" },
            { label: "value", valueType: "any" },
        ],
        outputs: [{ label: "result", valueType: "any" }],
        title: "Object Set",
        type: "object-set",
    },
    // Text
    {
        category: "text",
        description: "Joins two strings",
        icon: "+",
        inputs: [
            { label: "a", valueType: "text" },
            { label: "b", valueType: "text" },
        ],
        outputs: [{ label: "text", valueType: "text" }],
        title: "Concat",
        type: "text-concat",
    },
    {
        category: "text",
        description: "Splits a string by a delimiter",
        icon: "÷",
        inputs: [
            { label: "text", valueType: "text" },
            { label: "delimiter", valueType: "text" },
        ],
        outputs: [{ label: "parts", valueType: "any" }],
        title: "Split",
        type: "text-split",
    },
    {
        category: "text",
        description: "Checks if a string contains a substring",
        icon: "∈",
        inputs: [
            { label: "text", valueType: "text" },
            { label: "search", valueType: "text" },
        ],
        outputs: [{ label: "result", valueType: "boolean" }],
        title: "Contains",
        type: "text-contains",
    },
    {
        category: "text",
        description: "Tests a string against a regex pattern",
        icon: ".*",
        inputs: [
            { label: "text", valueType: "text" },
            { label: "pattern", valueType: "text" },
        ],
        outputs: [{ label: "match", valueType: "boolean" }],
        title: "Regex Match",
        type: "text-regex-match",
    },
    {
        category: "text",
        description: "Interpolates values into a template string",
        icon: "`$`",
        inputs: [
            { label: "template", valueType: "text" },
            { label: "values", valueType: "any" },
        ],
        outputs: [{ label: "result", valueType: "text" }],
        title: "Template",
        type: "text-template",
    },
    // Triggers
    {
        category: "trigger",
        description: "Fires when an HTTP webhook is received",
        icon: "⤵",
        inputs: [],
        outputs: [{ label: "payload", valueType: "any" }],
        title: "Webhook",
        type: "webhook-trigger",
    },
    {
        category: "trigger",
        description: "Fires on a recurring schedule",
        icon: "⏱",
        inputs: [],
        outputs: [{ label: "tick", valueType: "any" }],
        title: "Schedule",
        type: "schedule-trigger",
    },
    {
        category: "trigger",
        description: "Sends an HTTP request",
        icon: "⇄",
        inputs: [
            { label: "url", valueType: "text" },
            { label: "body", valueType: "any" },
        ],
        outputs: [
            { label: "response", valueType: "any" },
            { label: "status", valueType: "number" },
        ],
        title: "HTTP Request",
        type: "http-request",
    },
    // Flow control
    {
        category: "flow",
        description: "Passes through whichever input arrives first",
        icon: "⇒",
        inputs: [
            { label: "a", valueType: "any" },
            { label: "b", valueType: "any" },
        ],
        outputs: [{ label: "value", valueType: "any" }],
        title: "Merge",
        type: "flow-merge",
    },
    {
        category: "flow",
        description: "Collects values into an array",
        icon: "⊕",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [{ label: "batch", valueType: "any" }],
        title: "Batch",
        type: "flow-batch",
    },
    {
        category: "flow",
        description: "Broadcasts one value to multiple outputs",
        icon: "⑂",
        inputs: [{ label: "value", valueType: "any" }],
        outputs: [
            { label: "out 1", valueType: "any" },
            { label: "out 2", valueType: "any" },
            { label: "out 3", valueType: "any" },
        ],
        title: "Fan Out",
        type: "flow-fan-out",
    },
    // Annotation
    {
        category: "annotation",
        description: "A text note on the canvas",
        icon: "✎",
        inputs: [],
        outputs: [],
        styleVariant: "annotation",
        title: "Note",
        type: "annotation",
    },
];

export const workflowCategoryLabels: Record<WorkflowCategory, string> = {
    input: "Input",
    math: "Math",
    logic: "Logic",
    policy: "Policy",
    utility: "Utility",
    output: "Output",
    data: "Data",
    text: "Text",
    trigger: "Trigger",
    flow: "Flow",
    annotation: "Annotation",
};

export const workflowPresetByType = new Map(workflowPresets.map((preset) => [preset.type, preset]));

workflowPresetByType.set("policy-threshold", workflowPresetByType.get("policy-decision-table")!);
